### ISSUE TITLE
Riotfall isnt working

### ISSUE THREAD

**Issue by Frosty2332** [coastss/universal#1]
Riotfall isnt working

**Comment by lucciouss** [comment]
nothing is working lmfao this is ass

**Comment by coastss** [comment]
> nothing is working lmfao this is ass

And i aint gonna fix it either🤣🤣

**Comment by michtarxd** [comment]
@coastss Aimbot aims at empty space for me but thank You for sharing this super clean esp script <3

**Comment by lucciouss** [comment]
> > nothing is working lmfao this is ass
> 
> And i aint gonna fix it either🤣🤣

cuz u cant code retard kys skid

**Comment by coastss** [comment]
> > > nothing is working lmfao this is ass
> > 
> > 
> > And i aint gonna fix it either🤣🤣
> 
> cuz u cant code retard kys skid

No

**Comment by michtarxd** [comment]
@coastss Thanks for the script update 👍 Definitely the cleanest looking esp i've seen and it's open source
